// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ixxtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Ixxtension.3d8a4b56-1607-44a6-ba34-8f0ff85ee125";
        public const string Name = "Ixxtension";
        public const string Description = @"Visual studio extension to toggle between ixx/cpp files";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alexander Tuzhik";
        public const string Tags = "";
    }
}
