// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ixxtension
{
	internal sealed partial class Vsix
	{
		public const string Id = "Ixxtension.8215c260-7ef3-47ee-83d7-eb2a6e2f99ad";
		public const string Name = "Ixxtension";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "Alexander Tuzhik";
		public const string Tags = "";
	}
}
