// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ixxtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string IxxtensionString = "53fb8459-3e2c-478d-9054-56618645341c";
        public static Guid Ixxtension = new Guid(IxxtensionString);

        public const string guidImagesString = "2f30700a-020f-4193-b3c4-f7e96bb1ed8f";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int AboutCommand = 0x0100;
        public const int FileToggleCommand = 0x0101;
        public const int bmpInfo = 0x0001;
        public const int bmpToggle = 0x0002;
    }
}